CREATE TABLE IF NOT EXISTS public.measurements
(
    idmeasurements SERIAL PRIMARY KEY,
    "timestamp" TIMESTAMPTZ NOT NULL,
    amps_total SMALLINT NOT NULL,
    amps_phase_a SMALLINT NOT NULL,
    amps_phase_b SMALLINT NOT NULL,
    amps_phase_c SMALLINT NOT NULL,
    voltage_ln_average SMALLINT NOT NULL,
    phase_voltage_an SMALLINT NOT NULL,
    phase_voltage_bn SMALLINT NOT NULL,
    phase_voltage_cn SMALLINT NOT NULL,
    voltage_ll_average SMALLINT NOT NULL,
    phase_voltage_ab SMALLINT NOT NULL,
    phase_voltage_bc SMALLINT NOT NULL,
    phase_voltage_ca SMALLINT NOT NULL,
    frequency SMALLINT NOT NULL,
    total_real_power SMALLINT NOT NULL,
    watts_phase_a SMALLINT NOT NULL,
    watts_phase_b SMALLINT NOT NULL,
    watts_phase_c SMALLINT NOT NULL,
    ac_apparent_power_va SMALLINT NOT NULL,
    va_phase_a SMALLINT NOT NULL,
    va_phase_b SMALLINT NOT NULL,
    va_phase_c SMALLINT NOT NULL,
    reactive_power_var SMALLINT NOT NULL,
    var_phase_a SMALLINT NOT NULL,
    var_phase_b SMALLINT NOT NULL,
    var_phase_c SMALLINT NOT NULL,
    power_factor SMALLINT NOT NULL,
    pf_phase_a SMALLINT NOT NULL,
    pf_phase_b SMALLINT NOT NULL,
    pf_phase_c SMALLINT NOT NULL,
    total_real_energy_exported INTEGER NOT NULL,
    total_watt_hours_exported_in_phase_a INTEGER NOT NULL,
    total_watt_hours_exported_in_phase_b INTEGER NOT NULL,
    total_watt_hours_exported_in_phase_c INTEGER NOT NULL,
    total_real_energy_imported INTEGER NOT NULL,
    total_watt_hours_imported_phase_a INTEGER NOT NULL,
    total_watt_hours_imported_phase_b INTEGER NOT NULL,
    total_watt_hours_imported_phase_c INTEGER NOT NULL,
    total_va_hours_exported INTEGER NOT NULL,
    total_va_hours_exported_phase_a INTEGER NOT NULL,
    total_va_hours_exported_phase_b INTEGER NOT NULL,
    total_va_hours_exported_phase_c INTEGER NOT NULL,
    total_va_hours_imported INTEGER NOT NULL,
    total_va_hours_imported_phase_a INTEGER NOT NULL,
    total_va_hours_imported_phase_b INTEGER NOT NULL,
    total_va_hours_imported_phase_c INTEGER NOT NULL,
    total_var_hours_imported_q1 INTEGER NOT NULL,
    total_var_hours_imported_q1_phase_a INTEGER NOT NULL,
    total_var_hours_imported_q1_phase_b INTEGER NOT NULL,
    total_var_hours_imported_q1_phase_c INTEGER NOT NULL,
    total_var_hours_imported_q2 INTEGER NOT NULL,
    total_var_hours_imported_q2_phase_a INTEGER NOT NULL,
    total_var_hours_imported_q2_phase_b INTEGER NOT NULL,
    total_var_hours_imported_q2_phase_c INTEGER NOT NULL,
    total_var_hours_exported_q3 INTEGER NOT NULL,
    total_var_hours_exported_q3_phase_a INTEGER NOT NULL,
    total_var_hours_exported_q3_phase_b INTEGER NOT NULL,
    total_var_hours_exported_q3_phase_c INTEGER NOT NULL,
    total_var_hours_exported_q4 INTEGER NOT NULL,
    total_var_hours_exported_q4_phase_a INTEGER NOT NULL,
    total_var_hours_exported_q4_phase_b INTEGER NOT NULL,
    total_var_hours_exported_q4_phase_c INTEGER NOT NULL,
    serial_number TEXT COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT measurements_serial_number_fkey FOREIGN KEY (serial_number)
        REFERENCES public.meters (serial_number) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.measurements
    OWNER TO postgres;