CREATE SCHEMA IF NOT EXISTS demo AUTHORIZATION azure_pg_admin;
CREATE SCHEMA IF NOT EXISTS dev AUTHORIZATION azure_pg_admin;
CREATE SCHEMA IF NOT EXISTS production AUTHORIZATION azure_pg_admin;
CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION azure_pg_admin;