CREATE ROLE local_test_user WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1
	PASSWORD '12345678';
GRANT azure_pg_admin TO local_test_user WITH ADMIN OPTION;